language: cpp
compiler: 
    - gcc
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'versioninfo(); Pkg.init();'
    - julia -e 'Pkg.clone("git://github.com/JuliaStats/TimeSeries.jl"); Pkg.add("Dates"); Pkg.add("FactCheck"); Pkg.add("MarketData");'
    - mkdir -p ~/.julia/TimeSeries
    - cp -R ./* ~/.julia/TimeSeries/
    - julia --code-coverage ./test/runtests.jl
after_success:
    - julia -e 'cd(Pkg.dir("TimeSeries")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
